#!/bin/bash

# Função para realizar a adição
function adicao() {
  resultado=$(($1 + $2))
  echo "Resultado da adição: $resultado"
}

# Função para realizar a subtração
function subtracao() {
  resultado=$(($1 - $2))
  echo "Resultado da subtração: $resultado"
}

# Função para realizar a multiplicação
function multiplicacao() {
  resultado=$(($1 * $2))
  echo "Resultado da multiplicação: $resultado"
}

# Função para realizar a divisão
function divisao() {
  if [ $2 -eq 0 ]; then
    echo "Erro: Divisão por zero não é permitida."
  else
    resultado=$(($1 / $2))
    echo "Resultado da divisão: $resultado"
  fi
}

# Menu interativo
while true; do
  echo "Escolha a operação:"
  echo "1. Adição (+)"
  echo "2. Subtração (-)"
  echo "3. Multiplicação (*)"
  echo "4. Divisão (/)"
  echo "5. Sair"

  read -p "Opção: " opcao

  case $opcao in
    1)
      read -p "Digite o primeiro número: " num1
      read -p "Digite o segundo número: " num2
      adicao $num1 $num2
      ;;
    2)
      read -p "Digite o primeiro número: " num1
      read -p "Digite o segundo número: " num2
      subtracao $num1 $num2
      ;;
    3)
      read -p "Digite o primeiro número: " num1
      read -p "Digite o segundo número: " num2
      multiplicacao $num1 $num2
      ;;
    4)
      read -p "Digite o primeiro número: " num1
      read -p "Digite o segundo número: " num2
      divisao $num1 $num2
      ;;
    5)
      echo "Saindo da calculadora."
      exit 0
      ;;
    *)
      echo "Opção inválida. Por favor, escolha uma opção válida."
      ;;
  esac
done
